### ISSUE TITLE
Expedition 7: Leviathan - Save breaks after first death

### ISSUE THREAD

**Issue by SteveHow1ett** [cwmonkey/nms-expeditions#10]
hello, i have a problem with one milestone named Iterate/repeat. it tells me to kill myself, then run again my save. but when i run again my save, it doesn't load properly. all i see is a white screen, and after 2 minutes the game crashes. I can't play the expedition unfortunately. 

Help please

sorry for my english (google translate)

and sorry if I'm typing in the wrong place, I don't use github at all

Translated with DeepL.com (free version)

**Comment by cwmonkey** [comment]
@SteveHow1ett I am seeing the same issue. The new Orbital update may not be compatible with the "reset save on death" setting anymore. I'll see if I can come up with a fix.

**Comment by cwmonkey** [comment]
@SteveHow1ett Unfortunately I was unable to figure out how to make the broken save file playable again by just editing the `SEASON_DATA_CACHE.JSON` file. You will need to use a NMS save editor to make the save playable again. To do so, you will need to edit the save JSON and rename the `ExpeditionContext` key (or delete the object from the json if you know what you're doing).

Meanwhile, I have changed the Leviathan expedition to no longer reset the save on death. It sort of kills the idea behind the expedition, but you can now die regularly to finish the milestone.
