### ISSUE TITLE
Utopia expedition - cant save base to server

### ISSUE THREAD

**Issue by SteveHow1ett** [cwmonkey/nms-expeditions#13]
Hello, I found a problem in the utopia expedition, in the first phase there is a third quest "Upload your base to server", because I'm playing offline it probably won't work. 

I would be grateful for a solution

**Comment by cwmonkey** [comment]
@SteveHow1ett Are you sure you got the JSON from my site? https://cwmonkey.github.io/nms-expeditions/

All of the "upload base" milestones were replaced with other ones. The third milestone in the first phase has been changed to scanning 3 creatures.

You can download my JSON file for Utopia and replace the one you currently have in your cache folder. When you open your game up again it will replace all of the milestones that you can't do offline.

**Comment by SteveHow1ett** [comment]
Oh, My Bad, Sorry, I open old version
