### ISSUE TITLE
Expedition 8 with patch still giving pirate crew on freighter

### ISSUE THREAD

**Issue by ArbitraryHubris** [cwmonkey/nms-expeditions#15]
There is no commander, so you cannot access the logs per the expedition milestone on phase 1.   Patch was definitely checked: 
![image](https://github.com/user-attachments/assets/42d6e68d-1bd2-4928-a368-4b8992b276a4)

**Comment by ArbitraryHubris** [comment]
the freighter is pirate interior with civilian exterior

**Comment by ArbitraryHubris** [comment]
Update: after saving, exiting to desktop, and restarting the game, my crew is now not pirate and I'm able to access the log.   Very weird, but I'm now able to access the ship's log

**Comment by ArbitraryHubris** [comment]
issue resolved itself after restarting nms.

**Comment by cwmonkey** [comment]
@ArbitraryHubris How weird! I wish I knew exactly how to trigger the issue so I could test it. Regardless, thanks for the info, I'll add it to the note.
