### ISSUE TITLE
Expedition 7 - Unable to Claim Phase 5 Reward (and a workaround)

### ISSUE THREAD

**Issue by RotokEralil** [cwmonkey/nms-expeditions#16]
When trying to claim the final reward for phase 5 (the organic frigate) the game will crash. I have claimed all the other rewards (including the final rewards pack for doing all the phases), and only have the Phase 5 reward unclaimed.
A workaround is if you to the anomaly, you can end the expedition at the expedition terminal, and all the rewards (including the organic frigate) are available on all saves from the quicksilver merchant.

**Comment by cwmonkey** [comment]
Known issue mentioned on the site, but I'll update the note to include the part about the QS vendor.
